config/routes.rb
PetAdoption::Application.routes.draw do

  devise_for :users
  root "event_posts#index"
  get "event_posts/index"
  get "animal_posts/index"
  get "/adoptForm" => "pages#adoptForm"
  post "/adoptForm" => "pages#adoptForm"
  get "/volunteer" => "pages#volunteer"
  get "/volunteerForm" => "pages#volunteerForm"
  post "/volunteerForm" => "pages#volunteerForm"
  get "/foster" => "pages#foster"
  get "/fosterForm" => "pages#fosterForm"
  post "/fosterForm" => "pages#fosterForm"
  get "/donate" => "pages#donate"
  get "/about" => "pages#about"
  post "/about" => "pages#about"

  resources :animal_posts
  resources :event_posts
  

end

app/models/animal_post.rb
class AnimalPost < ActiveRecord::Base
end

app/models/event_post.rb
class EventPost < ActiveRecord::Base
end

app/models/role.rb
class Role < ActiveRecord::Base
	
	has_and_belongs_to_many :users
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
        devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

        has_and_belongs_to_many :roles

         def add_role(role)
         	self.roles << role
         end

         def add_role_by_name(role_name)
         	role = Role.find_by(name: role_name)
         	add_role(role)
         end

         def remove_role(role)
         	roles.delete(role)
         end

         def remove_role_by_name(role_name)
         	role = Role.find_by(name: role_name)
         	remove_role(role)
         end

         def is_role?(role) #Boolean function
         	roles.to_a.include?(role) #implied return for last line
         end

         def is_role_by_name?(role_name)
         	role = Role.find_by(name: role_name)
         	is_role?(role)
         end
end

app/controllers/animal_posts_controller.rb
class AnimalPostsController < ApplicationController
  
  before_action :deny_access_for_non_admins, except: [:index, :show]
  
  def index
  	@animal_posts = AnimalPost.all #variables with an @ are instance variables
  end

  def show
  	#uses the params hash to get the key (id for news_post)
  	@animal_post = AnimalPost.find(params[:id])

  end

  def new
    @animal_post = AnimalPost.new #dummy object to build the form
  end

  def create
    @animal_post = AnimalPost.new(animal_post_params)
    if @animal_post.save #saves to the database
      redirect_to @animal_post
    else
      # DO SOMETHING ELSE
    end
  end

  def edit
    @animal_post = AnimalPost.find(params[:id])
  end

  def update
    @animal_post = AnimalPost.find(params[:id]) #fetch an existing record

    if @animal_post.update(animal_post_params)
      redirect_to @animal_post #redirect to show - breaks rails conventions
    else
      # DO SOMETHING ELSE 
    end

  end

  def destroy
    @animal_post = AnimalPost.find(params[:id])
    @animal_post.destroy
    redirect_to animal_posts_path #redirect to index (all the newsposts) after destroy
  end


  private

    def animal_post_params
      params.require(:animal_post).permit(:name, :description, :birth, :vaccinated, :fertile) #sanitizes the hash
    end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

    def deny_access_for_non_admins
    	if current_user.nil? || !current_user.is_role_by_name?("admin")
    			
    	  redirect_to root_path 
    	  	
    	end
	end

end

app/controllers/event_posts_controller.rb
class EventPostsController < ApplicationController
  
before_action :deny_access_for_non_admins, except: [:index, :show]

  def index
  	@event_posts = EventPost.all #variables with an @ are instance variables
  end

  def show
  	#uses the params hash to get the key (id for news_post)
  	@event_post = EventPost.find(params[:id])

  end

  def new
    @event_post = EventPost.new #dummy object to build the form
  end

  def create
    @event_post = EventPost.new(event_post_params)
    if @event_post.save #saves to the database
      redirect_to @event_post
    else
      # DO SOMETHING ELSE
    end
  end

  def edit
    @event_post = EventPost.find(params[:id])
  end

  def update
    @event_post = EventPost.find(params[:id]) #fetch an existing record

    if @event_post.update(event_post_params)
      redirect_to @event_post #redirect to show - breaks rails conventions
    else
      # DO SOMETHING ELSE 
    end

  end

  def destroy
    @event_post = EventPost.find(params[:id])
    @event_post.destroy
    redirect_to event_posts_path #redirect to index (all the newsposts) after destroy
  end


  private

    def event_post_params
      params.require(:event_post).permit(:title, :date, :location, :description) #sanitizes the hash
    end


end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

	def home
	end

	def foster
		
	end
	
	def donate
	end

	def volunteer
	end

	def about
		if request.post? 
			# Send the e-mail
			first_name = params['first_name']
			last_name = params['last_name']
			email = params['email']
			message = params['message']
		UserMailer.contact_confirmation(email, first_name, last_name, message).deliver
			@success = true

		end
	end

	def adoptForm
		if request.post? 
			# Send the e-mail
			first_name = params['first_name']
			last_name = params['last_name']
			email = params['email']
			pet_name = params['pet_name']
			UserMailer.adopt_confirmation(email, first_name, last_name, pet_name).deliver
			@success = true

		end
	end

	def volunteerForm
		if request.post? 
			# Send the e-mail
			first_name = params['first_name']
			last_name = params['last_name']
			email = params['email']
			UserMailer.volunteer_confirmation(email, first_name, last_name).deliver
			@success = true

		end
	end

	def fosterForm
		if request.post? 
			# Send the e-mail
			first_name = params['first_name']
			last_name = params['last_name']
			email = params['email']
			UserMailer.foster_confirmation(email, first_name, last_name).deliver
			@success = true

		end
	end



end

app/helpers/animal_posts_helper.rb
module AnimalPostsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

	def admin?

		if current_user.nil? 
			false
		else
			current_user.is_role_by_name?("admin")
		end
	end

# Everything in these helpers is included everywhere except controllers

end

app/views/animal_posts/_animal_post.html.erb
<div class ="animal-post">

<%# Add each animal to the accordion table /#%>

    <section id="<%= animal_post.id %>">
        <h2>  <a href="#<%= animal_post.id %>"  > 
                            <b > <%= image_tag("#{animal_post.name}.jpg", :size => "100x75")%> </b>

                            
                            <b style= "font-weight: bold;width:15%"> <%= animal_post.name %> </b>
                            
                            
                            <b style="width:15%">  
                                <% number_of_days = (Date.today - animal_post.birth).to_i %>
                                <% number_of_years = (number_of_days /360).to_i %>

                                    <% if number_of_years == 1 %>
                                        <%= "%d year old" % number_of_years %>
                                    <% elsif number_of_years > 0 %>
                                        <%= "%d years old" % number_of_years %>
                                    <% end %>

                                    <% if number_of_years == 0 %>
                                        <% days_left = (number_of_days - (360*number_of_years)).to_i %>
                                        <% number_of_months = days_left / 30 %>

                                        <% if number_of_months == 1 %>
                                            <%= "%d month old" % number_of_months %>
                                        <% elsif number_of_months > 0 %>
                                            <%= "%d months old" % number_of_months %>
                                        <% end %>
                                    <% end %>

                                    <% if (number_of_years == 0) && (number_of_months == 0) %>
                                        <% number_of_weeks = ((days_left - (30*number_of_months)) / 7).to_i %>

                                        <% if number_of_weeks == 1 %>
                                            <%= "%d week old" % number_of_weeks%>
                                        <% elsif number_of_weeks > 0 %>
                                            <%= "%d weeks old" % number_of_weeks%>
                                        <% end %>
                                    <% end %>
                                </b>

                                
                                <b style="width:15%">  
                                    <% if animal_post.vaccinated == "yes" %>
                                        <%= "Vaccinated" %>
                                    <% else %>
                                        <%= "Unvaccinated" %>
                                    <% end %>
                                 </b>

                                 
                                <b style="width:23%">  
                                    <% if animal_post.fertile == "yes" %>
                                        <%= "Spayed/Neutered" %>
                                    <% else %>
                                        <%= "Not Spayed/Neutered" %>
                                    <% end %> 
                                </b>
                        </a>
                        
        </h2>   
        <p>
            <%= simple_format( animal_post.description) %><br>
            <br>
            <br>

            <% if admin? %>
               <%= link_to "Edit Animal Post", edit_animal_post_path(animal_post), class: "admin-link"  %>
               <br>
                 <%= link_to "Remove Animal Post",                       
                    animal_post, class: "admin-link" , method: :delete,  
                        confirm: "Are you sure you want to delete this animal post? " %>
                    <!-- this is a get resquest, add the argument call method to deal with delete (on surface a get but rails treats this as delete)--> <!-- "#" use a # as a dummy link-->
            <% end %>
            
        </p>  
    </section> 
</div>

app/views/animal_posts/_form.html.erb
<%=	form_for @animal_post do |f| %> 

	<div class="field">
		<%= f.label :name %><br>
		<%= f.text_field :name %><br>
	</div>
<br>
	<div class="field">
		<%= f.label :description %><br>
		<%= f.text_area :description %><br>
	</div>
<br>
	<div class="field">
		<%= f.label "Approximately when was the animal born?" %><br>
		<%= f.date_select :birth %><br>
	</div>
<br>
	<div class="field">
		<%= f.label "Has the animal had all necessary vaccinations?" %><br>
		<%= f.select :vaccinated, [['Yes','yes'],['No','no']]  %><br>
	</div>
<br>
	<div class="field">
		<%= f.label "Has the animal been spayed/neutered?" %><br>
		<%= f.select :fertile, [['Yes','yes'],['No','no']]  %><br>
	</div>
<br>

	<div class="actions">
		<%= f.submit %>
	</div>

<% end %>

app/views/animal_posts/edit.html.erb
<h1>Editing Animal Posts (<%=	@animal_post.name %>) </h1>

<%= render "form" %>

app/views/animal_posts/index.html.erb
<html>
<h1>All Animals</h1>

	Welcome to the adopt us section. Here you will find all the animals available for adoption. 
	<br>
	<br>
	<%= link_to image_tag("Order_form.png", :size => "45x60"), adoptForm_path %>
	<br>
  <%= link_to "Adoption Application", adoptForm_path, class: "reg-link"%>
  <br>


 

<% if admin? %>
<%= link_to "Add New Animal Posts", new_animal_post_path, class: "reg-link"  %>
<% end %>


	<div class="accordion vertical">

		<%= render @animal_posts %>

	</div>


</html>

app/views/animal_posts/new.html.erb
<h1>Add New Adoptable Animal</h1>

<%= render "form" %> <!---- if this form was under another folder you would have to do NameOfFolder/form >

app/views/animal_posts/show.html.erb
<h1> <%= @animal_post.name %></h1> 

<p>
	Description: <%= @animal_post.description %>
</p>


	<% if admin? %>
		<%= link_to "Edit Animal Post with ID:  #{@animal_post.id}", edit_animal_post_path(@animal_post), class: "reg-link"  %>
	<% end %>
	
<%= link_to "Back to All Animals", animal_posts_path, class: "reg-link"  %>

app/views/event_posts/_event_post.html.erb
<div class ="event-post">

<%# Add each animal to the accordion table /#%>

    <section id="<%= event_post.id %>">
        <h2 style="width:100%;height:100%">  <a href="#<%= event_post.id %>" style="width:100%;height:100%"> 

            <b style="font-weight:bold;width:40%"><%= event_post.title %></b>
            <b style="width:20%;"><%= event_post.date %></b>
            <b><%= event_post.location %></b>
                        </a>
                        
        </h2>   
        <p>
            <%= simple_format( event_post.description) %><br>
            <br>
            <br>

            <% if admin? %>
               <%= link_to "Edit Event Post", edit_event_post_path(event_post), class: "admin-link"  %>
               <br>
                 <%= link_to "Remove Event Post",                       
                    event_post, class: "admin-link" , method: :delete,  
                        confirm: "Are you sure you want to delete this event post? " %>
                    <!-- this is a get resquest, add the argument call method to deal with delete (on surface a get but rails treats this as delete)--> <!-- "#" use a # as a dummy link-->
            <% end %>
            
        </p>  
    </section> 
</div>

app/views/event_posts/_form.html.erb
<%=	form_for @event_post do |f| %> 
<div class = container>
	<div class = field>
		<%= f.label :title %><br>
		<%= f.text_field :title %><br>
	</div>

	<div class = field>
		<%= f.label :date %><br>
		<%= f.date_select :date %><br>
	</div>

	<div class = field>
		<%= f.label :location %><br>
		<%= f.text_field :location %><br>
	</div>

	<div class = field>
		<%= f.label :description %><br>
		<%= f.text_area :description %><br>
	</div>

	

	<div class = actions>
		<%= f.submit %>
	</div>
</div>
<% end %>

app/views/event_posts/edit.html.erb
<div class = container>
<h1>Editing Event Posts (<%=	@event_post.title %>) </h1>

<%= render "form" %>
</div>

app/views/event_posts/index.html.erb
<html>


	
	
		
		<h3>
			Mission Statement: <br>

			____ __ _______ _____ _ _____ ______ __ ______


		</h3>


		<br>
		<h1>
			Community Events
		</h1>

		<% if admin? %>
			<%= link_to "Add New Event Posts", new_event_post_path, class:"reg-link" %>
		<% end %>

		
	
			<div class="accordion vertical">

				<%= render @event_posts %>

			</div>
	
		



</html>

app/views/event_posts/new.html.erb
<div class = container>

<h1>New Event Post</h1>

<%= render "form" %> 

</div>

app/views/event_posts/show.html.erb
<div class = container>

<h1> <%= @event_post.title %></h1> 


<p>
	Date: <%= @event_post.date %>
</p>


<p>
	Location: <%= @event_post.location %>
</p>

<p>
	Description: <%= @event_post.description %>
</p>

<% if admin? %>
	<p>
		ID: <%= @event_post.id %>
	</p>

	<p>
		Updated: <%= @event_post.updated_at %>
	</p>

	<p>
		Created: <%= @event_post.created_at %>
	</p>

	<%= link_to "Edit Event Post with ID:  #{@event_post.id}", edit_event_post_path(@event_post) %>
<% end %>
<%= link_to "Back to All Events", event_posts_path %>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PetAdoption</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

	<div class="header" id="header">
		<div class ="container" id="header-container" >
			<%= image_tag("greyhound_silhouette.png", :size => "80x60")%>
			<h4 ><%= "Cat & Dog Rescue" %></h4>
			<%= image_tag("cat_silhouette.png", :size => "80x60")%>

		</div>
		
	</div>

<nav id='nav_bar'>
	<div class="navigation">
		<div class ="container" >
			<!---<%= image_tag "dog_silhouette.png"%> ADD LOGO PHOTO HERE-->
			<%= link_to "Home", root_path, class: "nav-link" %>
			<%= link_to "Adopt Us", animal_posts_path, class: "nav-link" %>
			<%= link_to "Volunteer", volunteer_path, class: "nav-link" %>
			<%= link_to "Foster", foster_path, class: "nav-link" %>
			<%= link_to "Donate", donate_path, class: "nav-link" %>
			<%= link_to "About", about_path, class: "nav-link" %>
			<% unless user_signed_in? %> <!--unless is equal to if not-->
				<%= link_to "Admin Sign In", new_user_session_path, class: "nav-link" %>
			<% end %>
			<% if user_signed_in? %>
				<% if admin? %>
				<%= link_to "Sign Out (Logged in as: Admin)", destroy_user_session_path, 
							method: :delete, class: "nav-link" %>
							<% else %>
							<%= link_to "Sign Out (Logged in as: Regular User)", destroy_user_session_path, 
							method: :delete, class: "nav-link" %>
							<% end %>

			<% end %>

		</div>
	</nav>

	</div>

	<div class="content">
		
			
			<%= yield %>

		
	</div>

	<footer id="footer">
		<div class = "container" >
	
			<br>
			<h2 style="padding-right:50px"> <%= "Contact Us" %></br> </h2>
			<%= "Phone Number: ____________"%></br>
			<%= "Email: ____________________" %></br>
			<%= "Address: __________________" %></br>
			<br>
		</div>
	</div>

</body>
</html>

app/views/pages/about.html.erb
<h1>About Us</h1>
<p> "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."</p>


<h3> To contact us please fill out the form below with your inquiry and we will be sure to get back to you shortly. Thank-you. </h3>
<% if @success %>
	Thank you for contacting us!
<% else %>
	<p>

		<%= form_tag do %>

		<div class="field">
			<%= label_tag :first_name, "First Name" %><br>
			<%= text_field_tag :first_name %><br>
		</div>

		<div class="field">
			<%= label_tag :last_name, "Last Name" %><br>
			<%= text_field_tag :last_name %><br>
		</div>

		<div class="field">
			<%= label_tag :email, "E-mail" %><br>
			<%= text_field_tag :email %><br>
		</div>

		<div class="field">
			<%= label_tag :message %><br>
			<%= text_area_tag :message %><br>
		</div>
		<br>

		<div class="field">
			<%= submit_tag "Submit" %>
		</div>

		<% end %>
	</p>
<% end %>

app/views/pages/adoptForm.html.erb
<h1>Adoption Application</h1>


<% if @success %>
	Thank you for submitting your adoption application!
<% else %>
	<p>

		<%= form_tag do %>

		<div class="field">
			<%= label_tag :first_name, "First Name" %><br>
			<%= text_field_tag :first_name %><br>
		</div>

		<div class="field">
			<%= label_tag :last_name, "Last Name" %><br>
			<%= text_field_tag :last_name %><br>
		</div>

		<div class="field">
			<%= label_tag :email, "E-mail" %><br>
			<%= text_field_tag :email %><br>
		</div>

		<div class="field">
			<%= label_tag :pet_name, "Pet Name" %><br>
			<%= text_area_tag :pet_name %><br>
		</div>
<br>
		<div class="field">
			<%= submit_tag "Submit" %>
		</div>

		<% end %>
	</p>

<% end %>

app/views/pages/donate.html.erb
<h1> Every little bit helps! </h1>
<br>
<br>
<div class="accordion vertical">
    <section id="Online" style= "height:auto">
        <h2 style ="height:auto">  
            <a href="#Online" style ="height:auto">Donate using Paypal </a>  </h2>
        <p>
            Even 10$ would help!<br>
            <br>
            <a href="https://www.paypal.com/home"  class=admin-link>Paypal Page</a>
                <!-- this is a get resquest, add the argument call method to deal with delete (on surface a get but rails treats this as delete)--> <!-- "#" use a # as a dummy link-->
        </p>  
    </section> 

        <section id="ByCheque" style= "height:auto">
        <h2 style ="height:auto">  <a href="#ByCheque" style ="height:auto">Donate By Cheque</a>  </h2>
        <p>
            Make the cheque out to: ______<br>
            <br>
            Mail to:<br>
             _________<br>
             _________<br>
             _________<br>
            <br>
            Or in person.
        </p>  
    </section> 

        <section id="Items" style= "height:auto">
        <h2 style ="height:auto">  <a href="#Items" style ="height:auto">Donate Items</a>  </h2>
        <p>
            We are currently in need of:<br>
            _______<br>
            _______<br>
            _______<br>
            _______<br>
        </p>  
    </section> 
 </div>
 <br>
 <br>
 <%= "Or hop on over to the " %>
 <%= link_to "Volunteer", volunteer_path, class: "reg-link" %>
 <%= "or " %>
 <%= link_to "Foster", foster_path, class: "reg-link" %>
 <%= " page to donate time instead!" %>

app/views/pages/foster.html.erb
<head>
<style> 
.subcontent{
	margin: 0;
            padding: 0;
            width:100%;
            min-height: 300px;
}
.policy
{
 position: relative;
            margin-right: 0px;

            width:47%;
            float:left;
            min-height:300px;
            border:5px outset #3B3835;
}
.openings
{
 float: right;
            text-align: left;
            width: 47%;
            min-height:300px;
            float:right;
            border:5px inset #3B3835;

}


</style>
</head>

<h1><%= "Welcome to the Foster page!"%></h1>

<p>
	<br>
	<br>
	<%= link_to image_tag("Order_form.png", :size => "45x60"), fosterForm_path %>
	<br>
	<%= link_to "Foster Application Form", fosterForm_path, class: "reg-link"%>
	<br>
	<br>
	Definition of Fostering: ____________________________________________
	<br>
	<br>
	<div class ="subcontent">
	<div class = "policy" style ="float:left">
		<br>
		Policies...
		<br>
		<ul>
		<li> _______________</li>
		<li> _______________</li>
		<li> _______________</li>
		<li> _______________</li>
		<li> _______________</li>
		<li> _______________</li>
		<li> _______________</li>
	</ul>
	</div>
	<div class = "openings" style="float:right">
		<br>
		Duties of fosterers...
		<br>
		<ul>
		<li> _______________</li>
		<li> _______________</li>
		<li> _______________</li>
		<li> _______________</li>
		<li> _______________</li>
		<li> _______________</li>
		<li> _______________</li>
		<br>
	</ul>
	</div>
</div>
	<br>
	<br>
	<%= "...or " %>
 <%= link_to "Volunteer", volunteer_path, class: "reg-link" %>
 <%= " instead!" %>

</p>

app/views/pages/fosterForm.html.erb
<h1>Foster Application</h1>


<% if @success %>
	Thank you for submitting your foster application!
<% else %>
	<p>

		<%= form_tag do %>

		<div class="field">
			<%= label_tag :first_name, "First Name" %><br>
			<%= text_field_tag :first_name %><br>
		</div>

		<div class="field">
			<%= label_tag :last_name, "Last Name" %><br>
			<%= text_field_tag :last_name %><br>
		</div>

		<div class="field">
			<%= label_tag :email, "E-mail" %><br>
			<%= text_field_tag :email %><br>
		</div>
			<br>

		
		<div class="field">
			<%= submit_tag "Submit" %>
		</div>

		<% end %>
	</p>

<% end %>

app/views/pages/home.html.erb
<!DOCTYPE html>
<html>

<body>
	<div class = "missionstatement" id = "missionstatement" >
		<div class = "container" id = "missionstatement-container" >
				Mission Statement: 

				Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
				tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
				quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
				consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
				cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
				proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
			
		</div>
	</div>
		
		

	<div class = "communityevents-title" id = "communityevents-title">
		<div class = "communityeventscontainer" id = "communityevents-container">
			Community Events

		</div>
	</div>

	<div class = "communityevents" id = "communityevents">
		<div class = "communityeventscontainer" id = "communityevents-container">
			Events	
		</div>
	</div>
		
	
</body>

app/views/pages/volunteer.html.erb
<head>
<style> 
.subcontent{
	margin: 0;
            padding: 0;
            width:100%;
            min-height: 300px;
}
.policy
{
 position: relative;
            margin-right: 0px;

            width:47%;
            float:left;
            min-height:300px;
            border:5px outset #3B3835;
}
.openings
{
 float: right;
            text-align: left;
            width: 47%;
            min-height:300px;
            float:right;
            border:5px inset #3B3835;

}


</style>
</head>

<h1><%= "Welcome to the Volunteer page!"%></h1>

<p>
	<br>
	<br>
	<%= link_to image_tag("Order_form.png", :size => "45x60"), volunteerForm_path %>
	<br>
	<%= link_to "Volunteer Application Form", volunteerForm_path, class: "reg-link"%>

	<br>
	<br>

	<div class = "subcontent">
	<div class = "policy" style ="float:left">
		<br>
		Policies...
		<br>
		<ul>
		<li> _______________</li>
		<li> _______________</li>
		<li> _______________</li>
		<li> _______________</li>
		<li> _______________</li>
		<li> _______________</li>
		<li> _______________</li>
	</ul>
	</div>

	<div class = "openings" style="float:right">
		<br>
		Tasks for volunteers...
		<br>
		<ul>
		<li> _______________</li>
		<li> _______________</li>
		<li> _______________</li>
		<li> _______________</li>
		<li> _______________</li>
		<li> _______________</li>
		<li> _______________</li>
		<br>
	</ul>
	</div>

</div>
	<br>
	<br>
	<%= "...or " %>
	<%= link_to "Foster", foster_path, class: "reg-link" %>
	<%= " instead!" %>

		</p>

app/views/pages/volunteerForm.html.erb
<h1>Volunteer Application</h1>


<% if @success %>
	Thank you for submitting your volunteering application!
<% else %>
	<p>

		<%= form_tag do %>

		<div class="field">
			<%= label_tag :first_name, "First Name" %><br>
			<%= text_field_tag :first_name %><br>
		</div>

		<div class="field">
			<%= label_tag :last_name, "Last Name" %><br>
			<%= text_field_tag :last_name %><br>
		</div>

		<div class="field">
			<%= label_tag :email, "E-mail" %><br>
			<%= text_field_tag :email %><br>
		</div>
<br>
		<div class="field">
			<%= submit_tag "Submit" %>
		</div>

		<% end %>
	</p>

<% end %>